# OT Security Testbed on Kathara with one P4 switch (single net-testbed network)

telegraf[0]="A1/02:11:00:00:00:11"
telegraf[image]="loriringhio97/otsec-telegraf-kathara-net:v1"
telegraf[volume]="../historian/telegraf/telegraf.conf|/etc/telegraf/telegraf.conf|ro"

influxdb[0]="A2/02:11:00:00:00:12"
influxdb[image]="loriringhio97/otsec-influxdb-kathara-net:v1"
influxdb[volume]="../historian/influxdb/influxdb.conf|/etc/influxdb/influxdb.conf|ro"

chronograf[0]="A3/02:11:00:00:00:13"
chronograf[image]="loriringhio97/otsec-chronograf-kathara-net:v1"

kapacitor[0]="A4/02:11:00:00:00:14"
kapacitor[image]="loriringhio97/otsec-kapacitor-kathara-net:v1"
kapacitor[volume]="../historian/kapacitor/kapacitor.conf|/etc/kapacitor/kapacitor.conf|ro"

industrial_process[0]="A5/02:11:00:00:00:20"
industrial_process[image]="loriringhio97/otsec-industrial-process-kathara-net:v1"

openplc[0]="A6/02:11:00:00:00:21"
openplc[image]="loriringhio97/otsec-openplc-kathara-net:v1"
openplc[volume]="../PLC/config.ini|/workdir/OpenPLC_v3/etc/config.ini|ro"

fuxa[0]="A7/02:11:00:00:00:22"
fuxa[image]="loriringhio97/otsec-fuxa-kathara-net:v1"

attacker[0]="A8/02:11:00:00:00:23"
attacker[image]="loriringhio97/otsec-attacker-kathara-net:v1"
attacker[sysctl]="net.ipv4.ip_forward=1"
attacker[sysctl]="net.ipv6.conf.all.forwarding=1"

shellinabox[0]="A9/02:11:00:00:00:24"
shellinabox[image]="loriringhio97/otsec-shellinabox-kathara-net:v1"
shellinabox[env]="SIAB_USER=attacker"
shellinabox[env]="SIAB_PASSWORD=attacker"
shellinabox[env]="SIAB_SSL=false"
shellinabox[env]="SIAB_PKGS=git zsh"
shellinabox[env]="SIAB_SUDO=false"

s1[0]="A1"
s1[1]="A2"
s1[2]="A3"
s1[3]="A4"
s1[4]="A5"
s1[5]="A6"
s1[6]="A7"
s1[7]="A8"
s1[8]="A9"
s1[image]="kathara/p4"
s1[mem]="6g"
s1[cpus]="2"
